AWSTemplateFormatVersion: '2010-09-09'
Description: 'TrulyYou - AWS Resources Setup (S3, IAM User with Amplify, Rekognition, and Cognito permissions)'

Parameters:
  DeploymentName:
    Type: String
    Description: Custom name for this deployment (e.g., 'production', 'staging', 'dev', or your company name)
    Default: production
    AllowedPattern: '^[a-z0-9][a-z0-9-]{0,30}[a-z0-9]$'
    ConstraintDescription: Must be lowercase, 2-32 characters, and contain only letters, numbers, and hyphens
  
  BucketName:
    Type: String
    Description: Name for the S3 bucket (leave default to auto-generate with deployment name)
    Default: ''

Conditions:
  UseDefaultBucketName: !Equals [!Ref BucketName, '']

Resources:
  # S3 Bucket for storing user data, liveness images, etc.
  TrulyYouBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !If 
        - UseDefaultBucketName
        - !Sub 'trulyyou-${DeploymentName}-${AWS::AccountId}'
        - !Ref BucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            AllowedOrigins:
              - '*'
            MaxAge: 3000
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: Application
          Value: TrulyYou
        - Key: ManagedBy
          Value: CloudFormation

  # IAM User for TrulyYou application
  TrulyYouIAMUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub 'trulyyou-${DeploymentName}-user'
      Tags:
        - Key: Application
          Value: TrulyYou
        - Key: ManagedBy
          Value: CloudFormation

  # Access Key for the IAM User
  TrulyYouAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref TrulyYouIAMUser

  # Cognito User Pool for user authentication
  TrulyYouUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub 'TrulyYou-${DeploymentName}'
      AutoVerifiedAttributes:
        - email
      Schema:
        - Name: email
          AttributeDataType: String
          Required: true
          Mutable: false
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
      Tags:
        - Key: Application
          Value: TrulyYou
        - Key: Environment
          Value: !Ref DeploymentName
        - Key: ManagedBy
          Value: CloudFormation

  # Cognito User Pool Client
  TrulyYouUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub 'TrulyYou-${DeploymentName}-Client'
      UserPoolId: !Ref TrulyYouUserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH

  # Cognito Identity Pool for AWS resource access
  TrulyYouIdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      IdentityPoolName: !Sub 'TrulyYou_${DeploymentName}'
      AllowUnauthenticatedIdentities: true
      CognitoIdentityProviders:
        - ClientId: !Ref TrulyYouUserPoolClient
          ProviderName: !GetAtt TrulyYouUserPool.ProviderName

  # IAM Role for authenticated Cognito users
  CognitoAuthenticatedRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'TrulyYou-${DeploymentName}-CognitoAuthRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                cognito-identity.amazonaws.com:aud: !Ref TrulyYouIdentityPool
              ForAnyValue:StringLike:
                cognito-identity.amazonaws.com:amr: authenticated
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
      Tags:
        - Key: Application
          Value: TrulyYou
        - Key: Environment
          Value: !Ref DeploymentName
        - Key: ManagedBy
          Value: CloudFormation

  # IAM Role for unauthenticated Cognito users
  CognitoUnauthenticatedRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'TrulyYou-${DeploymentName}-CognitoUnauthRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                cognito-identity.amazonaws.com:aud: !Ref TrulyYouIdentityPool
              ForAnyValue:StringLike:
                cognito-identity.amazonaws.com:amr: unauthenticated
      Tags:
        - Key: Application
          Value: TrulyYou
        - Key: Environment
          Value: !Ref DeploymentName
        - Key: ManagedBy
          Value: CloudFormation

  # Attach roles to Identity Pool
  IdentityPoolRoleAttachment:
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    Properties:
      IdentityPoolId: !Ref TrulyYouIdentityPool
      Roles:
        authenticated: !GetAtt CognitoAuthenticatedRole.Arn
        unauthenticated: !GetAtt CognitoUnauthenticatedRole.Arn

  # IAM Policy for S3 full access to the bucket
  TrulyYouS3Policy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub 'TrulyYou-${DeploymentName}-S3Access'
      Users:
        - !Ref TrulyYouIAMUser
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: S3FullAccess
            Effect: Allow
            Action:
              - s3:*
            Resource:
              - !GetAtt TrulyYouBucket.Arn
              - !Sub '${TrulyYouBucket.Arn}/*'

  # IAM Policy for Rekognition (facial recognition, liveness detection)
  TrulyYouRekognitionPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub 'TrulyYou-${DeploymentName}-RekognitionAccess'
      Users:
        - !Ref TrulyYouIAMUser
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: RekognitionFullAccess
            Effect: Allow
            Action:
              - rekognition:*
            Resource: '*'
          - Sid: RekognitionServiceRole
            Effect: Allow
            Action:
              - iam:GetRole
              - iam:PassRole
            Resource: '*'
            Condition:
              StringEquals:
                iam:PassedToService: rekognition.amazonaws.com

  # IAM Policy for Amplify (if needed for hosting/CI/CD)
  TrulyYouAmplifyPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub 'TrulyYou-${DeploymentName}-AmplifyAccess'
      Users:
        - !Ref TrulyYouIAMUser
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AmplifyFullAccess
            Effect: Allow
            Action:
              - amplify:*
            Resource: '*'

  # IAM Policy for Cognito (user authentication/management)
  TrulyYouCognitoPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub 'TrulyYou-${DeploymentName}-CognitoAccess'
      Users:
        - !Ref TrulyYouIAMUser
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: CognitoFullAccess
            Effect: Allow
            Action:
              - cognito-identity:*
              - cognito-idp:*
              - cognito-sync:*
            Resource: '*'

  # IAM Policy for CloudFront (CDN for faster content delivery)
  TrulyYouCloudFrontPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub 'TrulyYou-${DeploymentName}-CloudFrontAccess'
      Users:
        - !Ref TrulyYouIAMUser
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: CloudFrontFullAccess
            Effect: Allow
            Action:
              - cloudfront:*
            Resource: '*'

  # IAM Policy for Lambda (if needed for serverless functions)
  TrulyYouLambdaPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub 'TrulyYou-${DeploymentName}-LambdaAccess'
      Users:
        - !Ref TrulyYouIAMUser
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: LambdaFullAccess
            Effect: Allow
            Action:
              - lambda:*
            Resource: '*'
          - Sid: LambdaLogging
            Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: 'arn:aws:logs:*:*:*'

Outputs:
  DeploymentName:
    Description: The deployment/environment name for this stack
    Value: !Ref DeploymentName
  
  BucketName:
    Description: Name of the S3 bucket
    Value: !Ref TrulyYouBucket
    Export:
      Name: !Sub '${AWS::StackName}-BucketName'

  BucketArn:
    Description: ARN of the S3 bucket
    Value: !GetAtt TrulyYouBucket.Arn
    Export:
      Name: !Sub '${AWS::StackName}-BucketArn'

  IAMUserName:
    Description: Name of the IAM user
    Value: !Ref TrulyYouIAMUser
    Export:
      Name: !Sub '${AWS::StackName}-IAMUserName'

  AccessKeyId:
    Description: Access Key ID for the IAM user (COPY THIS - it won't be shown again)
    Value: !Ref TrulyYouAccessKey

  SecretAccessKey:
    Description: Secret Access Key for the IAM user (COPY THIS - it won't be shown again)
    Value: !GetAtt TrulyYouAccessKey.SecretAccessKey

  Region:
    Description: AWS Region where resources were created
    Value: !Ref AWS::Region
  
  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref TrulyYouUserPool
    Export:
      Name: !Sub '${AWS::StackName}-UserPoolId'
  
  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref TrulyYouUserPoolClient
    Export:
      Name: !Sub '${AWS::StackName}-UserPoolClientId'
  
  IdentityPoolId:
    Description: Cognito Identity Pool ID
    Value: !Ref TrulyYouIdentityPool
    Export:
      Name: !Sub '${AWS::StackName}-IdentityPoolId'

  SetupInstructions:
    Description: Next steps
    Value: !Sub 'TrulyYou (${DeploymentName}) - Copy the TrulyYouSetupJSON below and paste it into the setup form'
  
  TrulyYouSetupJSON:
    Description: 'COPY THIS JSON - Complete AWS configuration for TrulyYou setup (paste into "Import from JSON" on setup page)'
    Value: !Sub |
      {
        "awsAccessKeyId": "${TrulyYouAccessKey}",
        "awsSecretAccessKey": "${TrulyYouAccessKey.SecretAccessKey}",
        "awsRegion": "${AWS::Region}",
        "s3Bucket": "${TrulyYouBucket}",
        "cognitoUserPoolId": "${TrulyYouUserPool}",
        "cognitoUserPoolClientId": "${TrulyYouUserPoolClient}",
        "cognitoIdentityPoolId": "${TrulyYouIdentityPool}"
      }

